site_name: SC940 Board Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    scheme: default
    primary: indigo
    accent: indigo

copyright: Copyright &copy; 2025 Essensys

nav:
  - Accueil: index.md
  - Architecture:
    - Vue d'Ensemble: Architecture_Overview.md
    - Budget Puissance: Power_Budget.md
  - Conception Matérielle:
    - Fichiers de Conception: hardware.md
    - Journal des Modifications: Hardware_ChangeLog.md
    - Recommandations DFM: DFM_Recommendations.md
  - Firmware: firmware.md
  - Téléchargements: downloads.md

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
